import { chromium } from 'playwright-core'
const browser = await chromium.launch({ channel: 'msedge' })
const page = await browser.newPage({ viewport: { width: 1366, height: 768 } })
await page.goto('http://localhost:5199/src/sim/worlds/distribusi/ui/preview.html?v=3d')
await page.waitForTimeout(2200)
// Rotate 90° and zoom in.
await page.evaluate(() => (document.querySelector('[aria-label="Putar 90°"]')).click())
await page.waitForTimeout(400)
await page.evaluate(() => (document.querySelector('[aria-label="Perbesar"]')).click())
await page.waitForTimeout(400)
await page.evaluate(() => (document.querySelector('[aria-label="Perbesar"]')).click())
await page.waitForTimeout(600)
await page.screenshot({ path: '.sim-local/v1-rotated-zoom.png' })
console.log('rotated shot ok')
// Reset + interior view (roof fade).
await page.evaluate(() => (document.querySelector('[aria-label="Reset tampilan"]')).click())
await page.evaluate(() => (document.querySelector('[aria-label="Lihat dalam gudang"]')).click())
await page.waitForTimeout(700)
await page.screenshot({ path: '.sim-local/v1-interior.png' })
console.log('interior shot ok')
await browser.close()
