// Seed import (BRIEF §7): seed/board-export.json → database, idempotent, upserting on legacy_id.
//
//   node scripts/import-seed.ts sql    [--owner-email a@b] [--email m-david=x@y …] > import.sql
//   node scripts/import-seed.ts verify-sql                                       > verify.sql
//   node scripts/import-seed.ts run --db-url postgres://…  [--owner-email …] [--email …]
//
// `run` applies the import in one transaction with psql, then prints the verification report and
// exits 1 on any mismatch. Re-running updates planning fields (titles, dates, PIC, pemeriksa,
// milestones, dependencies, steps) but never touches workflow state (stage, commitment, evidence,
// decisions). E-mail addresses are parameters, never stored in the repository.
import { spawnSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { lit } from './reference-sql.ts'

interface SeedTask {
  id: string
  projectId: string
  milestoneId: string
  title: string
  desc: string
  start: string
  end: string
  assignee: string
  validator: string
  proof: string
  stage: string
  deps: string[]
  steps?: string[]
  createdAt: number
}
interface SeedExport {
  projects: { id: string; name: string; entity: string; outcome: string; measure: string; owner: string; status: string; maturity: string; gateMode: boolean; color: string; createdAt: number }[]
  members: { id: string; name: string; role: string; access: string; emailDaily: boolean; createdAt: number }[]
  milestones: { id: string; projectId: string; code: string; title: string; target: string; criteria: string; trigger: string; fallback: string; approver: string; mode: string; order: number; createdAt: number }[]
  tasks: SeedTask[]
  asks: { id: string; projectId: string; milestoneId: string; question: string; decider: string; due: string; status: string; createdAt: number; createdBy: string }[]
}

export const PROJECT_LEGACY = 'samb-timeline'
export const PROJECT_NAME = 'Project Margin Bridge'
export const TEMPLATE_NAME = 'Trading SAMB'
/** BRIEF §7: m-dika and m-david are pm, m-yani and m-muti officer on Margin Bridge. */
export const MEMBERSHIP: Record<string, 'pm' | 'officer'> = { 'm-dika': 'pm', 'm-david': 'pm', 'm-yani': 'officer', 'm-muti': 'officer' }
export const OWNER_LEGACY = 'm-dika'

const seedPath = new URL('../seed/board-export.json', import.meta.url)
export const readSeed = (): SeedExport => JSON.parse(readFileSync(seedPath, 'utf8')) as SeedExport

const ts = (ms: number) => `to_timestamp(${ms / 1000})`
const date = (s: string) => (s ? `${lit(s)}::date` : 'null')
const person = (legacy: string) => (legacy ? `(select id from public.people where legacy_id = ${lit(legacy)})` : 'null')
const project = `(select id from public.projects where legacy_id = ${lit(PROJECT_LEGACY)})`
const milestone = (legacy: string) =>
  legacy ? `(select id from public.milestones where project_id = ${project} and legacy_id = ${lit(legacy)})` : 'null'
const task = (legacy: string) => `(select id from public.tasks where project_id = ${project} and legacy_id = ${lit(legacy)})`

export interface ImportOptions {
  ownerEmail?: string
  /** legacy person id → e-mail */
  emails?: Record<string, string>
}

export function buildImportSql(seed: SeedExport, opts: ImportOptions = {}): string {
  const p = seed.projects.find((x) => x.id === PROJECT_LEGACY)
  if (!p) throw new Error(`Project ${PROJECT_LEGACY} not in the export`)
  const L: string[] = ['-- Generated by scripts/import-seed.ts', 'begin;', '']

  L.push('-- people (BRIEF §7: display_name = name, job_title = role)')
  for (const m of seed.members) {
    L.push(
      `insert into public.people (legacy_id, display_name, job_title, email_daily, created_at) values (${lit(m.id)}, ${lit(m.name)}, ${lit(m.role)}, ${m.emailDaily !== false}, ${ts(m.createdAt)})`,
      `  on conflict (legacy_id) do update set display_name = excluded.display_name, job_title = excluded.job_title;`,
    )
  }
  const emails = { ...(opts.emails ?? {}), ...(opts.ownerEmail ? { [OWNER_LEGACY]: opts.ownerEmail } : {}) }
  for (const [legacy, email] of Object.entries(emails)) {
    L.push(
      `insert into public.people_contact (person_id, email) values (${person(legacy)}, ${lit(email)})`,
      `  on conflict (person_id) do update set email = excluded.email;`,
    )
  }
  if (opts.ownerEmail) {
    L.push(
      `-- owner role for ${OWNER_LEGACY}: granted now if the login exists, otherwise when it is created`,
      `insert into public.app_roles (user_id, role) select u.id, 'owner' from auth.users u where lower(u.email) = lower(${lit(opts.ownerEmail)}) on conflict do nothing;`,
      `insert into public.pending_app_roles (email, role) select ${lit(opts.ownerEmail)}, 'owner'`,
      `  where not exists (select 1 from auth.users u where lower(u.email) = lower(${lit(opts.ownerEmail)})) on conflict do nothing;`,
    )
  }

  L.push('', '-- project')
  L.push(
    `insert into public.projects (legacy_id, name, entity_code, outcome, measure, status, maturity, gate_mode, parallel_gates, color, step_template_id, created_at)`,
    `values (${lit(PROJECT_LEGACY)}, ${lit(PROJECT_NAME)}, ${lit(p.entity)}, ${lit(p.outcome)}, ${lit(p.measure)}, ${lit(p.status || 'aktif')}, ${lit(p.maturity)}, ${p.gateMode !== false}, false, ${lit(p.color || 'samb3')},`,
    `        (select id from public.step_templates where name = ${lit(TEMPLATE_NAME)}), ${ts(p.createdAt)})`,
    `on conflict (legacy_id) do update set name = excluded.name, entity_code = excluded.entity_code, outcome = excluded.outcome,`,
    `  measure = excluded.measure, maturity = excluded.maturity, color = excluded.color, step_template_id = excluded.step_template_id;`,
  )

  L.push('', '-- memberships (derived, BRIEF §7)')
  for (const [legacy, role] of Object.entries(MEMBERSHIP)) {
    L.push(
      `insert into public.project_members (project_id, person_id, role) values (${project}, ${person(legacy)}, ${lit(role)})`,
      `  on conflict (project_id, person_id) do update set role = excluded.role;`,
    )
  }
  L.push(`update public.projects set pm_person_id = ${person(p.owner)} where legacy_id = ${lit(PROJECT_LEGACY)};`)

  L.push('', '-- milestones (code from code, sort_order from order)')
  for (const m of seed.milestones.filter((x) => x.projectId === PROJECT_LEGACY)) {
    L.push(
      `insert into public.milestones (project_id, legacy_id, code, title, target, criteria, trigger, fallback, approver_person_id, mode, sort_order, created_at)`,
      `values (${project}, ${lit(m.id)}, ${m.code ? lit(m.code) : 'null'}, ${lit(m.title)}, ${date(m.target)}, ${lit(m.criteria)}, ${lit(m.trigger)}, ${lit(m.fallback)}, ${person(m.approver)}, ${lit(m.mode || 'slow')}, ${m.order}, ${ts(m.createdAt)})`,
      `on conflict (project_id, legacy_id) do update set code = excluded.code, title = excluded.title, target = excluded.target, criteria = excluded.criteria,`,
      `  trigger = excluded.trigger, fallback = excluded.fallback, approver_person_id = excluded.approver_person_id, mode = excluded.mode, sort_order = excluded.sort_order;`,
    )
  }

  const tasks = seed.tasks.filter((t) => t.projectId === PROJECT_LEGACY)
  L.push('', '-- tasks (planning fields only on conflict; workflow state is never reset)')
  for (const t of tasks) {
    L.push(
      `insert into public.tasks (project_id, milestone_id, legacy_id, title, description, start_date, end_date, assignee_person_id, validator_person_id, proof_requested, stage, committed, created_at)`,
      `values (${project}, ${milestone(t.milestoneId)}, ${lit(t.id)}, ${lit(t.title)}, ${lit(t.desc)}, ${date(t.start)}, ${date(t.end)}, ${person(t.assignee)}, ${person(t.validator)}, ${lit(t.proof)}, ${lit(t.stage || 'todo')}, false, ${ts(t.createdAt)})`,
      `on conflict (project_id, legacy_id) do update set milestone_id = excluded.milestone_id, title = excluded.title, description = excluded.description,`,
      `  start_date = excluded.start_date, end_date = excluded.end_date, assignee_person_id = excluded.assignee_person_id,`,
      `  validator_person_id = excluded.validator_person_id, proof_requested = excluded.proof_requested;`,
    )
  }

  L.push('', '-- dependencies and value-chain steps: replaced for imported tasks')
  L.push(`delete from public.task_deps where task_id in (select id from public.tasks where project_id = ${project} and legacy_id is not null);`)
  for (const t of tasks)
    for (const dep of t.deps ?? [])
      L.push(`insert into public.task_deps (project_id, task_id, depends_on_task_id) values (${project}, ${task(t.id)}, ${task(dep)});`)
  L.push(`delete from public.task_steps where task_id in (select id from public.tasks where project_id = ${project} and legacy_id is not null);`)
  for (const t of tasks)
    for (const code of t.steps ?? [])
      L.push(
        `insert into public.task_steps (task_id, template_step_id) select ${task(t.id)}, s.id from public.template_steps s join public.step_templates st on st.id = s.template_id where st.name = ${lit(TEMPLATE_NAME)} and s.code = ${lit(code)};`,
      )

  L.push('', '-- asks (question, due, milestone on conflict; decisions are never reset)')
  for (const a of seed.asks.filter((x) => x.projectId === PROJECT_LEGACY)) {
    L.push(
      `insert into public.asks (project_id, milestone_id, legacy_id, question, decider_person_id, due, status, created_at, created_by)`,
      `values (${project}, ${milestone(a.milestoneId)}, ${lit(a.id)}, ${lit(a.question)}, ${person(a.decider)}, ${date(a.due)}, ${lit(a.status || 'open')}, ${ts(a.createdAt)}, ${person(a.createdBy)})`,
      `on conflict (project_id, legacy_id) do update set question = excluded.question, due = excluded.due, milestone_id = excluded.milestone_id;`,
    )
  }
  L.push('', 'commit;', '')
  return L.join('\n')
}

/** Expected counts from BRIEF §7 (taken from the export on 6 Oct 2026). */
export const EXPECTED: [string, string][] = [
  ['projects', '1'],
  ['milestones', '13'],
  ['tasks', '59'],
  ['tasks without milestone', 'TB-DES,TB-JAN,TB-NOV,TB-OKT'],
  ['tasks with an assignee', '39'],
  ['tasks with a validator', '59'],
  ['tasks committed', '0'],
  ['tasks with ≥1 step', '28'],
  ['task_steps rows', '38'],
  ['task_deps rows', 'CAP-NOV→MB27,TB-NOV→MB27,TB-OKT→MB21'],
  ['asks', '8'],
  ['people', '4'],
  ['project_members', '4'],
]

export function buildVerifySql(): string {
  const t = `public.tasks t where t.project_id = ${project}`
  return [
    `select 'projects', count(*)::text from public.projects where legacy_id = ${lit(PROJECT_LEGACY)}`,
    `select 'milestones', count(*)::text from public.milestones where project_id = ${project}`,
    `select 'tasks', count(*)::text from ${t}`,
    `select 'tasks without milestone', string_agg(t.legacy_id, ',' order by t.legacy_id) from ${t} and t.milestone_id is null`,
    `select 'tasks with an assignee', count(*)::text from ${t} and t.assignee_person_id is not null`,
    `select 'tasks with a validator', count(*)::text from ${t} and t.validator_person_id is not null`,
    `select 'tasks committed', count(*)::text from ${t} and t.committed`,
    `select 'tasks with ≥1 step', count(distinct ts.task_id)::text from public.task_steps ts join public.tasks t on t.id = ts.task_id where t.project_id = ${project}`,
    `select 'task_steps rows', count(*)::text from public.task_steps ts join public.tasks t on t.id = ts.task_id where t.project_id = ${project}`,
    `select 'task_deps rows', string_agg(dep.legacy_id || '→' || tk.legacy_id, ',' order by dep.legacy_id || '→' || tk.legacy_id) from public.task_deps d join public.tasks tk on tk.id = d.task_id join public.tasks dep on dep.id = d.depends_on_task_id where d.project_id = ${project}`,
    `select 'asks', count(*)::text from public.asks where project_id = ${project}`,
    `select 'people', count(*)::text from public.people where legacy_id in (${Object.keys(MEMBERSHIP).map(lit).join(', ')})`,
    `select 'project_members', count(*)::text from public.project_members where project_id = ${project}`,
  ].join('\nunion all\n') + ';\n'
}

/** Compares psql output ("check|actual" lines) with EXPECTED; returns the report and whether it passed. */
export function report(output: string): { text: string; ok: boolean } {
  const actual = new Map(
    output
      .trim()
      .split('\n')
      .filter(Boolean)
      .map((l) => {
        const i = l.indexOf('|')
        return [l.slice(0, i), l.slice(i + 1)] as const
      }),
  )
  let ok = true
  const rows = EXPECTED.map(([check, want]) => {
    const have = actual.get(check) ?? '(missing)'
    const pass = have === want
    ok &&= pass
    return `${pass ? 'OK  ' : 'FAIL'}  ${check.padEnd(26)} expected ${want.padEnd(38)} actual ${have}`
  })
  return { text: ['Verification report (BRIEF §7)', ...rows, ok ? 'All counts match.' : 'MISMATCH: import did not reproduce the export.'].join('\n'), ok }
}

function parseArgs(argv: string[]) {
  const opts: ImportOptions & { dbUrl?: string } = { emails: {} }
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    const v = argv[i + 1] ?? ''
    if (a === '--owner-email') {
      opts.ownerEmail = v
      i++
    } else if (a === '--db-url') {
      opts.dbUrl = v
      i++
    } else if (a === '--email') {
      const [k, e] = v.split('=')
      if (k && e) opts.emails![k] = e
      i++
    }
  }
  return opts
}

function psql(dbUrl: string, sql: string): string {
  const r = spawnSync('psql', [dbUrl, '-X', '-q', '-t', '-A', '-v', 'ON_ERROR_STOP=1', '-f', '-'], { input: sql, encoding: 'utf8' })
  if (r.status !== 0) throw new Error(r.stderr || `psql exited with ${r.status}`)
  return r.stdout
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const [cmd, ...rest] = process.argv.slice(2)
  const opts = parseArgs(rest)
  if (cmd === 'sql') process.stdout.write(buildImportSql(readSeed(), opts))
  else if (cmd === 'verify-sql') process.stdout.write(buildVerifySql())
  else if (cmd === 'run') {
    const url = opts.dbUrl ?? process.env.SUPABASE_DB_URL
    if (!url) throw new Error('Pass --db-url or set SUPABASE_DB_URL.')
    psql(url, buildImportSql(readSeed(), opts))
    const r = report(psql(url, buildVerifySql()))
    console.log(r.text)
    process.exit(r.ok ? 0 : 1)
  } else {
    console.error('Usage: node scripts/import-seed.ts sql|verify-sql|run [--db-url …] [--owner-email …] [--email legacy=addr …]')
    process.exit(2)
  }
}
