// Builds the reference-data migration (entities, holidays, the "Trading SAMB" step template)
// from the seed JSON, so the database and the package files cannot drift apart.
//   node scripts/reference-sql.ts            → rewrites the migration
// tests/reference-sql.test.ts fails if the committed migration differs from this output.
import { readFileSync, writeFileSync } from 'node:fs'

export const MIGRATION_PATH = 'supabase/migrations/20261006000500_reference_data.sql'

interface EntitiesFile { entities: { code: string; label: string; sort: number }[] }
interface HolidaysFile { holidays: { date: string; type: string; name: string; source: string }[] }
interface TemplateFile {
  meta: { name: string }
  steps: { code: string; label_no: string; name: string; need: string; kind: string; sort: number }[]
}

const root = new URL('..', import.meta.url)
const readJson = <T>(path: string): T => JSON.parse(readFileSync(new URL(path, root), 'utf8')) as T

export const lit = (v: string | number | null): string =>
  v === null ? 'null' : typeof v === 'number' ? String(v) : `'${v.replaceAll("'", "''")}'`

export function buildReferenceSql(): string {
  const entities = readJson<EntitiesFile>('seed/entities.json').entities
  const holidays = readJson<HolidaysFile>('seed/holidays.json').holidays
  const template = readJson<TemplateFile>('seed/step-template-trading-samb.json')

  const rows = (values: string[]) => values.map((v) => `  (${v})`).join(',\n')
  return [
    '-- Generated by scripts/reference-sql.ts from seed/entities.json, seed/holidays.json and',
    '-- seed/step-template-trading-samb.json. Do not edit by hand; rerun the script instead.',
    '',
    'insert into public.entities (code, label, sort) values',
    rows(entities.map((e) => [lit(e.code), lit(e.label), lit(e.sort)].join(', '))) + ';',
    '',
    'insert into public.holidays (date, type, name, source) values',
    rows(holidays.map((h) => [lit(h.date), lit(h.type), lit(h.name), lit(h.source)].join(', '))) + ';',
    '',
    `with t as (insert into public.step_templates (name) values (${lit(template.meta.name)}) returning id)`,
    'insert into public.template_steps (template_id, code, label_no, name, need, kind, sort)',
    'select t.id, s.code, s.label_no, s.name, s.need, s.kind, s.sort from t, (values',
    rows(template.steps.map((s) => [lit(s.code), lit(s.label_no), lit(s.name), lit(s.need), lit(s.kind), lit(s.sort)].join(', '))),
    ') as s (code, label_no, name, need, kind, sort);',
    '',
  ].join('\n')
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(new URL(MIGRATION_PATH, root), buildReferenceSql())
  console.log(`Wrote ${MIGRATION_PATH}`)
}
